### ISSUE TITLE
Aloitin transifex osuuden selvittelyn

### ISSUE THREAD

**Issue by kyyberi** [q2a-suomi/q2a-suomikaannos#2]
Aloin testaamaan mitä kaikkea pitää asentaa ja konffata että saa vedettyä käännökset omaan lokaaliin repoon.

**Comment by markosu** [comment]
Hyvin toimi skripti kun kokeilin. Säädin päivittäisen ajon toimimaan.
Täytyy vielä säätää niin, että skripti siirtää githubiin vain käännetyt ja katselmoidut käännökset.
